version: '3'
services:

  app:
    image: docker.pkg.github.com/alnat/moneykeeper/moneykeeper:latest
    container_name: moneykeeper
    # Передаем параметры соединения с БД
    environment:
      - spring.datasource.url=jdbc:postgresql://localhost:5432/moneykeeper
      - spring.datasource.username=moneykeeper
      - spring.datasource.password=moneykeeper
    ports:
      - "8080:8080"
