name: Docker CI

on:
  # На все коммиты в master
  push:
    branches:
      - 'master'
      - 'feature/docker' # TODO УДАЛИТЬ ПОСЛЕ ТЕСТИРОВАНИЯ!


jobs:
  # Сборки через Maven и прогон всех тестов
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify

  # Сборка и публикация Docker образа
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:

      # Сборка Jar
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean compile package

      # Установка глобальных переменных
      - name: set global env
        id: global_env
        run: |
          echo "::set-output name=IMAGE_NAME::moneykeeper"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/alnat/moneykeeper/moneykeeper"

      # Сборка образа
      - name: Build and tag image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .

      # Вход в registry под учеткой
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      # Публикация образа
      - name: Publish image
        env:
          IMAGE_NAME: alnat/moneykeeper:latest
        run: docker push "docker.pkg.github.com/alnat/moneykeeper/${{ steps.global_env.outputs.IMAGE_NAME }}"
